while{true} do{
	_debug = true;
	_detect = false; 
	_draw = 0;
	_action = 0;
	_fobject = "";
	if(isNull cursorObject)then{
			if(_action == 0)then{}else{player removeAction _action };}
	else{  
player removeAction _action;
removeMissionEventHandler ["Draw3D",_draw];	
		_actionModel = (getModelinfo cursorObject select 0);
	systemchat format ["cursorObject:%1",(str _actionModel)];	
		_array = [
	"WoodPile_F.p3d",
	"Timbers_F.p3d",
	"Bricks_V1_F.p3d", 
	"Bricks_V2_F.p3d", 
	"Bricks_V3_F.p3d",	
	"Bricks_V4_F.p3d", 
	"CinderBlocks_F.p3d",  
	"IronPipes_F.p3d",
	"Pipes_large_F.p3d",
	"Pipes_small_F.p3d",
	"WoodenBox_F.p3d",
	"WorkStand_F.p3d",
	"Pallet_F.p3d",
	"Pallet_vertical_F.p3d", 
	"Pallets_F.p3d",  
	"Garbage_line_F.p3d",
	"Garbage_square3_F.p3d",
	"Garbage_square5_F.p3d",
	"GarbageBags_F.p3d",
	"GarbagePallet_F.p3d", 
	"GarbageWashingMachine_F.p3d",
	"JunkPile_F.p3d",
	"Tyre_F.p3d",
	"Tyres_F.p3d",
	"CratesWooden_F.p3d",
	"MarketShelter_F.p3d",
	"Sack_F.p3d",	
	"Sacks_goods_F.p3d", 
	"WoodenCart_F.p3d",
	"CargoBox_V1_F.p3d",
	"Cargo20_blue_F.p3d",
	"Cargo20_brick_red_F.p3d",
	"Cargo20_cyan_F.p3d",
	"Cargo20_grey_F.p3d",
	"Cargo20_light_blue_F.p3d",
	"Cargo20_light_green_F.p3d",
	"Cargo20_military_green_F.p3d",
	"Cargo20_orange_F.p3d",
	"Cargo20_red_F.p3d",
	"Cargo20_sand_F.p3d",
	"Cargo20_white_F.p3d",
	"Cargo20_yellow_F.p3d",
	"Cargo40_blue_F.p3d",
	"Cargo40_brick_red_F.p3d",
	"Cargo40_cyan_F.p3d",
	"Cargo40_grey_F.p3d",
	"Cargo40_light_blue_F.p3d",
	"Cargo40_light_green_F.p3d",
	"Cargo40_military_green_F.p3d",
	"Cargo40_orange_F.p3d",
	"Cargo40_red_F.p3d",
	"Cargo40_sand_F.p3d",
	"Cargo40_white_F.p3d",
	"Cargo40_yellow_F.p3d",
	"BagFence_Corner_F.p3d",
	"BagFence_End_F.p3d",
	"BagFence_Long_F.p3d",
	"BagFence_Round_F.p3d",
	"BagFence_Short_F.p3d",
	"HBarrier_1_F.p3d",
	"HBarrier_3_F.p3d",
	"HBarrier_5_F.p3d",
	"HBarrierBig_F.p3d",
	"HBarrierTower_F.p3d",
	"Razorwire_F.p3d", 
	"Shoot_House_Wall_F.p3d",
	"Shoot_House_Wall_Stand_F.p3d",
	"Shoot_House_Wall_Crouch_F.p3d",
	"Shoot_House_Wall_Prone_F.p3d",
	"Shoot_House_Wall_Long_F.p3d",
	"Shoot_House_Wall_Long_Stand_F.p3d",
	"Shoot_House_Wall_Long_Prone_F.p3d",
	"Shoot_House_Panels_F.p3d",
	"Shoot_House_Panels_Vault_F.p3d",
	"Obstacle_Climb_F.p3d",
	"Obstacle_Cross_F.p3d",
	"Obstacle_RunAround_F.p3d",
	"Obstacle_Saddle_F.p3d",
	"Metal_Pole_F.p3d",
	"Metal_Pole_Platform_F.p3d",
	"Metal_Pole_Skeet_F.p3d",
	"RowBoat_V1_F.p3d",
	"RowBoat_V2_F.p3d",
	"RowBoat_V3_F.p3d",
	"Ancient_Wall_4m_F.p3d",
	"Ancient_Wall_8m_F.p3d",
	"BarGate_F.p3d",
	"Canal_Wall_10m_F.p3d",
	"Canal_Wall_D_center_F.p3d",
	"Canal_Wall_D_left_F.p3d",
	"Canal_Wall_D_right_F.p3d",
	"Canal_Wall_Stairs_F.p3d",
	"Canal_WallSmall_10m_F.p3d",
	"City_4m_F.p3d",
	"City_8m_F.p3d",
	"City_8mD_F.p3d",
	"City_Gate_F.p3d",
	"City_Pillar_F.p3d",
	"City2_4m_F.p3d",
	"City2_8m_F.p3d",
	"City2_PillarD_F.p3d",
	"CncBarrier_F.p3d",
	"CncBarrier_stripes_F.p3d",
	"CncBarrierMedium_F.p3d",
	"CncBarrierMedium4_F.p3d",
	"CncShelter_F.p3d",
	"CncWall1_F.p3d",
	"CncWall4_F.p3d",
	"Crash_barrier_F.p3d",
	"Mil_ConcreteWall_F.p3d",
	"Mil_WallBig_4m_F.p3d",
	"Mil_WallBig_Corner_F.p3d",
	"Mil_WallBig_Gate_F.p3d",
	"Mil_WiredFence_F.p3d",
	"Net_Fence_8m_F.p3d",
	"Net_Fence_Gate_F.p3d",
	"Net_FenceD_8m_F.p3d",
	"New_WiredFence_5m_F.p3d",
	"New_WiredFence_10m_Dam_F.p3d",
	"New_WiredFence_10m_F.p3d",
	"Pipe_Fence_4m_F.p3d",
	"Pipe_Fence_4mNoLC_F.p3d",
	"PipeWall_concretel_8m_F.p3d",
	"Slums01_8m.p3d",
	"Slums02_4m.p3d",
	"SportGround_Fence_F.p3d",
	"Stone_4m_F.p3d",
	"Stone_8m_F.p3d",
	"Stone_8mD_F.p3d",
	"Stone_Gate_F.p3d",
	"Wall_IndCnc_2deco_F.p3d",
	"Wall_IndCnc_4_D_F.p3d",
	"Wall_IndCnc_4_F.p3d",
	"Wall_Tin_4.p3d",
	"Wall_Tin_4_2.p3d",
	"Wired_Fence_4m_F.p3d",
	"Wired_Fence_4mD_F.p3d",
	"Wired_Fence_8m_F.p3d",
	"Wired_Fence_8mD_F.p3d",
	"WoodenLog_F.p3d",		
	"WoodenTable_large_F.p3d",
	"WoodenTable_small_F.p3d",
	"Bench_F.p3d",
	"ChairWood_F.p3d",
	"Metal_wooden_rack_F.p3d",
	"Rack_F.p3d",
	"ShelvesWooden_blue_F.p3d",
	"TableDesk_F.p3d",
	"HeatPump_F.p3d",
	"Metal_rack_F.p3d",
	"Metal_rack_Tall_F.p3d",
	"ShelvesMetal_F.p3d",
	"Metal_Shed_ruins_F.p3d",
	"Cargo20_color_V1_ruins_F.p3d",
	"Cargo20_color_V2_ruins_F.p3d",
	"Cargo20_color_V3_ruins_F.p3d",
	"Cargo20_china_color_V1_ruins_F.p3d",
	"Cargo20_china_color_V2_ruins_F.p3d",
	"Cargo20_military_ruins_F.p3d",
	"Cargo40_color_V1_ruins_F.p3d",
	"Cargo40_color_V2_ruins_F.p3d",
	"Cargo40_color_V3_ruins_F.p3d",
	"Cargo40_china_color_V1_ruins_F.p3d",
	"Cargo40_china_color_V2_ruins_F.p3d",
	"Cargo40_military_ruins_F.p3d",
	"cmp_Hopper_ruins_F.p3d",
	"Factory_Conv1_Main_ruins_F.p3d",
	"Factory_Conv2_ruins_F.p3d",
	"Factory_Hopper_ruins_F.p3d",
	"ReservoirTank_Airport_ruins_F.p3d",
	"ReservoirTank_Rust_ruins_F.p3d",
	"ReservoirTank_V1_ruins_F.p3d",
	"ReservoirTower_ruins_F.p3d",
	"Shed_Big_ruins_F.p3d",
	"Shed_Small_ruins_F.p3d",
	"Shed_Ind_ruins_F.p3d",
	"TTowerBig_1_ruins_F.p3d",
	"TTowerBig_2_ruins_F.p3d",
	"Land PowerGenerator F.p3d",
	"BarrelWater_F.p3d",
	"WaterBarrel_F.p3d",
	"WaterTank_F.p3d",
	"CanisterFuel_F.p3d",
	"CanisterOil_F.p3d",
	"MetalBarrel_F.p3d",
	"Cargo_House_V1_ruins_F.p3d",
	"Cargo_House_V2_ruins_F.p3d",
	"Cargo_House_V3_ruins_F.p3d",
	"Cargo_HQ_V1_ruins_F.p3d",
	"Cargo_HQ_V2_ruins_F.p3d",
	"Cargo_HQ_V3_ruins_F.p3d",
	"Cargo_Patrol_V1_ruins_F.p3d",
	"Cargo_Patrol_V2_ruins_F.p3d",
	"Cargo_Patrol_V3_ruins_F.p3d",
	"Cargo_Tower_V1_ruins_F.p3d",
	"Cargo_Tower_V2_ruins_F.p3d",
	"Cargo_Tower_V3_ruins_F.p3d",
	"Medevac_house_V1_ruins_F.p3d",
	"Medevac_HQ_V1_ruins_F.p3d",
	"GarbageContainer_closed_F.p3d",
	"GarbageContainer_open_F.p3d",
	"ShelvesWooden_F.p3d",
	"ShelvesWooden_khaki_F.p3d",
	"BarrelWater_grey_F.p3d",
	"Sunshade_01_F.p3d",
	"Sunshade_02_F.p3d",
	"Sunshade_03_F.p3d",
	"Sunshade_04_F.p3d",
	"GarbageBarrel_01_F.p3d",
	"GarbageBin_01_F.p3d",
	"Sign_Mines_F.p3d",
	"Sign_WarningMilAreaSmall_F.p3d",
	"Sign_WarningMilitaryArea_F.p3d",
	"Sign_WarningMilitaryVehicles_F.p3d",
	"Sign_WarningUnexplodedAmmo_F.p3d",
	"Sign_Direction_F.p3d",
	"FlagChecked_F.p3d",
	"FlagSmall_F.p3d",
	"Sign_F.p3d",
	"RoadCone_L_F.p3d",
	"RoadBarrier_F.p3d",
	"RoadBarrier_small_F.p3d",
	"Pole_F.p3d",
	"TapeSign_F.p3d",
	"ArrowDesk_L_F.p3d",
	"ArrowDesk_R_F.p3d",
	"ArrowMarker_R_F.p3d",
	"ArrowMarker_L_F.p3d",
	"SignAd_Sponsor_F.p3d",
	"SignAd_Sponsor_Vrana_F.p3d",
	"SignAd_Sponsor_ARMEX_F.p3d",
	"SignAd_Sponsor_Quontrol_F.p3d",
	"SignAd_Sponsor_ION_F.p3d",
	"SignAd_Sponsor_Larkin_F.p3d",
	"SignAd_SponsorS_F.p3d",
	"SignAd_SponsorS_Vrana_F.p3d",
	"SignAd_SponsorS_ARMEX_F.p3d",
	"SignAd_SponsorS_Quontrol_F.p3d",
	"SignAd_SponsorS_ION_F.p3d",
	"SignAd_SponsorS_Larkin_F.p3d",
	"UWreck_FishingBoat_F.p3d",
	"UWreck_Heli_Attack_02_F.p3d",
	"UWreck_MV22_F.p3d",
	"Wreck_BMP2_F.p3d",
	"Wreck_BRDM2_F.p3d",
	"Wreck_Car_F.p3d",
	"Wreck_Car2_F.p3d",
	"Wreck_Car3_F.p3d",
	"Wreck_CarDismantled_F.p3d",
	"Wreck_Heli_Attack_01_F.p3d",
	"Wreck_Heli_Attack_02_F.p3d",
	"Wreck_HMMWV_F.p3d",
	"Wreck_Hunter_F.p3d",
	"Wreck_Offroad_F.p3d",
	"Wreck_Offroad2_F.p3d",
	"Wreck_Plane_Transport_01_F.p3d",
	"Wreck_Skodovka_F.p3d",
	"Wreck_Slammer_F.p3d",
	"Wreck_Slammer_hull_F.p3d",
	"Wreck_Slammer_turret_F.p3d",
	"Wreck_T72_hull_F.p3d",
	"Wreck_T72_turret_F.p3d",
	"Wreck_Traw_F.p3d",
	"Wreck_Traw2_F.p3d",
	"Wreck_Truck_dropside_F.p3d",
	"Wreck_Truck_F.p3d",
	"Wreck_UAZ_F.p3d",
	"Wreck_Ural_F.p3d",
	"Wreck_Van_F.p3d",
	"Scrap_MRAP_01_F.p3d",
	"ScrapHeap_1_F.p3d",
	"ScrapHeap_2_F.p3d",
	"cages_f.p3d"];  

		_arraylength = (count _array-1); 
		
		
		if(_debug)then{systemchat format ["Checking Objects:%1",_arraylength]; };												
															

		for "_i" from 0 to _arraylength do  					
		{   
			if(_actionModel == _array select _i)then
			{ 
				_fobject = _array select _i;
				_detect = true;
				systemchat str"detected";
				
				
			};
										
		};  
		systemchat format ["detected:%1",_detect];
		if(_detect)then{
		_distObj = getpos player distance getpos cursorObject;
		_posObj = getPos cursorObject;
		hint str "found something";
		systemchat format ["distance:%1",_distObj];
			if(_distObj <= 50)then{
			systemchat format ["Found Object in Range:%1",(str _actionModel)];
			systemchat format ["Position Object in Range:%1",(str _posObj)];
			_draw = addMissionEventHandler ["Draw3D", {
					drawIcon3D ["", [1,0,0,1], position cursorObject, 0, 0, 0, "Use", 1, 0.05, "PuristaMedium"];
				}];
			_action = player addAction["Look",[_action] execVM "look.sqf"] };
			}
			else{systemchat format ["detected:%1",_detect];
			};
				
	};
uisleep 2;
};
